import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {ThemeProvider} from "@/components/theme-provider"
import Navbar from "@/components/navbar";
import {ModeToggle} from "@/components/mode-toggle";
import React from "react";
import {ConvexAuthNextjsServerProvider} from "@convex-dev/auth/nextjs/server";
import {ConvexClientProvider} from "@/app/ConvexClientProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
            <ThemeProvider
                attribute="class"
                defaultTheme="system"
                enableSystem
                disableTransitionOnChange
            >
                <ConvexClientProvider>
                    <Navbar/>
                    {children}
                </ConvexClientProvider>
                <div className="fixed bottom-4 right-4">
                    <ModeToggle/>
                </div>
            </ThemeProvider>
            </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
